# Generated by Django 5.0.6 on 2024-07-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='Project',
            new_name='project',
        ),
    ]
